version: "3.9"

services:
  auth-service:
    build:
      context: ./auth-service
    ports:
      - 8070:8070

  google-maps-adapter:
    build:
      context: ./google-maps-adapter
    ports:
      - 8080:8080
