version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./db/0_init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ./db/1_schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./db/2_seed.sql:/docker-entrypoint-initdb.d/2_seed.sql
      - ./db/3_demo.sql:/docker-entrypoint-initdb.d/3_demo.sql
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=delivery_service
      - POSTGRES_USER=sde
      - POSTGRES_PASSWORD=sde@2020
    ports:
      - 5432:5432
  redis:
    image: redis:alpine

  auth-service:
    build:
      context: ./auth-service
    ports:
      - 8070:8070
    environment:
      DATA_SERVICE_URL: "http://data-service:8080"

  google-maps-adapter:
    build:
      context: ./google-maps-adapter
    ports:
      - 8080:8080

  shipment-service:
    build:
      context: ./shipment-service
    ports:
      - 8090:8090
    environment:
      DATA_SERVICE_URL: "http://data-service:8080"
  data-service:
    build:
      context: ./data-service
    ports:
      - 8081:8080
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${PG_DATABASE:-delivery_service}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-sde@2020}
      POSTGRES_USER: sde

  location-service:
    build:
      context: ./location-service
    ports:
      - 8082:8080
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  shipper-assignment-service:
    build:
      context: ./shipper-assignment-service
    ports:
      - 8083:8080
    environment:
      DATA_SERVICE_URL: "http://data-service:8080"
      LOCATION_SERVICE_URL: "http://location-service:8080"
      RADIUS_LIMIT: "200km"
  trip-service:
    build:
      context: ./trip-service
    ports:
      - 8085:8080
    environment:
      DATA_SERVICE_URL: "http://data-service:8080"
  delivery-service:
    build:
      context: ./delivery-service
    ports:
      - 8084:8080
    environment:
      SHIPMENT_SERVICE_URL: "http://shipment-service:8090"
      GOOGLEMAP_SERVICE_URL: "http://google-maps-adapter:8080"
      SHIPPER_ASSIGNMENT_SERVICE_URL: "http://shipper-assignment-service:8080"
      TRIP_SERVICE_URL: "http://trip-service:8080"
      TELEGRAM_BOT_URL: "http://telegram-bot:8060"
      MAXIMUM_WAIT_TIME: 50000
      REJECT_WAIT_TIME: 60000

  telegram-bot:
    build:
      context: ./telegram-bot
    ports:
      - 8060:8060
    environment:
      USER_SERVICE_URL: "http://auth-service:8070"
      SHIPMENT_SERVICE_URL: "http://shipment-service:8090"
      GOOGLEMAP_SERVICE_URL: "http://google-maps-adapter:8080"
      DELIVERY_SERVICE_URL: "http://delivery-service:8080"
      LOCATION_SERVICE_URL: "http://location-service:8080"
      STATUS_SERVICE_URL: "http://status-service:8050"

  status-service:
    build:
      context: ./status-service
    ports:
      - 8050:8050
    environment:
      SHIPMENT_SERVICE_URL: "http://shipment-service:8090"
      TRIP_SERVICE_URL: "http://trip-service:8080"
      TELEGRAM_BOT_URL: "http://telegram-bot:8060"

volumes:
  postgres_data:
