package it.unitn.sde.shipperassignmentservice.constant;

public enum StatusEnum {
    PARTY_ENABLED, PARTY_DISABLED, DELIVERY_REQUEST_CREATED, DELIVERY_REQUEST_ACCEPTED, DELIVERY_REQUEST_PROCESSING,
    DELIVERY_REQUEST_DELIVERIED, DELIVERY_REQUEST_REJECTED, TRIP_STARTED, TRIP_FINISHED, POINT_ASSIGNED, POINT_PROCESSED

}
