package it.unitn.sde.tripservice.constant;

public enum StatusEnum {
    PARTY_ENABLED, PARTY_DISABLED, DELIVERY_REQUEST_CREATED, DELIVERY_REQUEST_ACCEPTED, DELIVERY_REQUEST_PROCESSING,
    DELIVERY_REQUEST_DELIVERIED, TRIP_CREATED, TRIP_ACCEPTED, TRIP_PROCESSING, TRIP_FINISHED, POINT_ASSIGNED, POINT_PROCESSED

}
