module.exports = {
    DELIVERY_STATUS_CREATED: "DELIVERY_REQUEST_CREATED",
    DELIVERY_STATUS_ACCEPTED: "DELIVERY_REQUEST_ACCEPTED",
    DELIVERY_STATUS_REJECTED: "DELIVERY_REQUEST_REJECTED",
    DELIVERY_STATUS_PROCESSING: "DELIVERY_REQUEST_PROCESSING",
    DELIVERY_STATUS_DELIVERED: "DELIVERY_REQUEST_DELIVERIED",
    POINT_ASSIGNED: "POINT_ASSIGNED",
    POINT_PROCESSED: "POINT_PROCESSED"
}